# 1. Data Processing

## Importing all the nesessary Libraries

In [28]:
 import pandas as pd
 from pathlib import Path

# Path to the repo's dataset folder
# path = Path("Datasets")
# # Combines your folder name and the *.csv pattern into a list of CSV files.
# all_files = sorted(path.glob("*.csv"))

# #The loop (processing each file)
# ## li-- Initializes an empty list to hold the data from each file temporarily.
# li =[]

# for filename in all_files:
#     df = pd.read_csv(filename, sep=";", index_col = None, header=0)
#     #Tagging the Data 
#     df['Patient_ID'] = filename.stem
#     li.append(df)

# #Merging everything

# combined_activity = pd.concat(li, axis= 0,ignore_index = True)
# combined_activity.to_csv("Combined_Datasets.csv", index=False)

IndentationError: unexpected indent (2172452370.py, line 1)

In [27]:
# checking the Shape and top rows
print(f"Total rows and columns:{combined_activity.shape}")
print(combined_activity.head())

Total rows and columns:(309392, 9)
                  time  glucose  calories  heart_rate  steps  basal_rate  \
0  2018-06-13T18:40:00    332.0    6.3595   82.322835   34.0    0.091667
1  2018-06-13T18:45:00    326.0    7.7280   83.740157    0.0    0.091667
2  2018-06-13T18:50:00    330.0    4.7495   80.525180    0.0    0.091667
3  2018-06-13T18:55:00    324.0    6.3595   89.129032   20.0    0.091667
4  2018-06-13T19:00:00    306.0    5.1520   92.495652    0.0    0.075000

   bolus_volume_delivered  carb_input Patient_ID
0                     0.0         0.0  HUPA0001P
1                     0.0         0.0  HUPA0001P
2                     0.0         0.0  HUPA0001P
3                     0.0         0.0  HUPA0001P
4                     0.0         0.0  HUPA0001P

In [10]:
combined_activity.head

<bound method NDFrame.head of                        time     glucose  calories  heart_rate  steps  \
0       2018-06-13T18:40:00  332.000000   6.35950   82.322835   34.0
1       2018-06-13T18:45:00  326.000000   7.72800   83.740157    0.0
2       2018-06-13T18:50:00  330.000000   4.74950   80.525180    0.0
3       2018-06-13T18:55:00  324.000000   6.35950   89.129032   20.0
4       2018-06-13T19:00:00  306.000000   5.15200   92.495652    0.0
...                     ...         ...       ...         ...    ...
309387  2022-05-18T11:55:00  109.333333  10.79280  104.171171    0.0
309388  2022-05-18T12:00:00  114.000000   9.80346  103.442623    0.0
309389  2022-05-18T12:05:00  118.666667   5.66622   95.542857    0.0
309390  2022-05-18T12:10:00  123.333333   5.57628   91.381356    0.0
309391  2022-05-18T12:15:00  128.000000   5.57628   99.257812    0.0

        basal_rate  bolus_volume_delivered  carb_input Patient_ID
0         0.091667                     0.0         0.0  HUPA0001P
1         0.091667                     0.0         0.0  HUPA0001P
2         0.091667                     0.0         0.0  HUPA0001P
3         0.091667                     0.0         0.0  HUPA0001P
4         0.075000                     0.0         0.0  HUPA0001P
...            ...                     ...         ...        ...
309387    0.000000                     0.0         0.0  HUPA0028P
309388    0.000000                     0.0         0.0  HUPA0028P
309389    0.000000                     0.0         0.0  HUPA0028P
309390    0.000000                     0.0         0.0  HUPA0028P
309391    0.000000                     0.0         0.0  HUPA0028P

[309392 rows x 9 columns]>

# Reading csv files for 11-15 patients

In [15]:
path = Path("11-15_Patients")
# Combines your folder name and the *.csv pattern into a list of CSV files.
all_files = sorted(path.glob("*.csv"))

#The loop (processing each file)
## li-- Initializes an empty list to hold the data from each file temporarily.
li =[]

for filename in all_files:
    df = pd.read_csv(filename, sep=";", index_col = None, header=0)
    #Tagging the Data 
    df['Patient_ID'] = filename.stem
    li.append(df)

#Merging everything

combined_activity = pd.concat(li, axis= 0,ignore_index = True)
combined_activity.to_csv("Combined_Datasets_11-15.csv", index=False)

# Rounding the columns to 3 decimals

In [19]:
cols=['calories','glucose','heart_rate','steps','basal_rate']
df[cols]=df[cols].round(3)
df.head()

,time,glucose,calories,heart_rate,steps,basal_rate,bolus_volume_delivered,carb_input,Patient_ID
0,2019-03-28T12:00:00,81.000,7.157,91.664,13.0,0.059,0.0,0.0,HUPA0017P
1,2019-03-28T12:05:00,74.667,8.016,82.906,19.0,0.059,0.0,0.0,HUPA0017P
2,2019-03-28T12:10:00,68.333,5.153,79.400,48.0,0.059,0.0,0.0,HUPA0017P
3,2019-03-28T12:15:00,62.000,6.298,78.126,0.0,0.059,0.0,0.0,HUPA0017P
4,2019-03-28T12:20:00,60.000,9.734,86.033,38.0,0.059,0.0,0.0,HUPA0017P

In [20]:
df.dtypes

time                       object
glucose                   float64
calories                  float64
heart_rate                float64
steps                     float64
basal_rate                float64
bolus_volume_delivered    float64
carb_input                float64
Patient_ID                 object
dtype: object

# Change time data type to datetime

In [22]:
df['time']=pd.to_datetime(df['time'])

# Renaming columns to proper format

In [23]:
df = df.rename(columns={
    'Patient_ID': 'Patient ID',
    'time': 'Time',
    'glucose': 'Glucose',
    'calories': 'Calories',
    'heart_rate': 'Heart Rate',
    'steps': 'Steps',
    'basal_rate': 'Basal Rate',
    'bolus_volume_delivered': 'Bolus Volume Delivered',
    'carb_input': 'Carb Input'
})

# Checking for Outliers

In [24]:
numeric_cols = [
    'Glucose',
    'Calories',
    'Heart Rate',
    'Steps',
    'Basal Rate',
    'Bolus Volume Delivered',
    'Carb Input'
]

Q1 = df[numeric_cols].quantile(0.25)
Q3 = df[numeric_cols].quantile(0.75)
IQR = Q3 - Q1

outliers = (
    df[numeric_cols] < (Q1 - 1.5 * IQR)
) | (
    df[numeric_cols] > (Q3 + 1.5 * IQR)
)

outliers.sum()

Glucose                     0
Calories                  219
Heart Rate                 10
Steps                     515
Basal Rate                  0
Bolus Volume Delivered     29
Carb Input                 35
dtype: int64

In [25]:
df.head()

,Time,Glucose,Calories,Heart Rate,Steps,Basal Rate,Bolus Volume Delivered,Carb Input,Patient ID
0,2019-03-28 12:00:00,81.000,7.157,91.664,13.0,0.059,0.0,0.0,HUPA0017P
1,2019-03-28 12:05:00,74.667,8.016,82.906,19.0,0.059,0.0,0.0,HUPA0017P
2,2019-03-28 12:10:00,68.333,5.153,79.400,48.0,0.059,0.0,0.0,HUPA0017P
3,2019-03-28 12:15:00,62.000,6.298,78.126,0.0,0.059,0.0,0.0,HUPA0017P
4,2019-03-28 12:20:00,60.000,9.734,86.033,38.0,0.059,0.0,0.0,HUPA0017P